{
 "title": "Fraud Detection Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "% Per Risk Level (1h)",
   "type": "piechart",
   "description": "Shows percentage and total count of transactions per each risk level for the last 1 hour ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fraud-metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"fraud_events\" and r._field == \"fraud_score\")\r\n  |> group(columns: [\"risk_level\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({\r\n      risk_level: r.risk_level,\r\n      count: r._value\r\n  }))\r\n  |> keep(columns: [\"risk_level\", \"count\"])\r\n"
    }
   ]
  },
  {
   "title": "Activity (1h)",
   "type": "timeseries",
   "description": "Displays incoming fraud events from the last hour, with lower fraud scores (closer to 0) appearing at the bottom and higher scores (closer to 1) at the top of the chart",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fraud-metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"fraud_events\")"
    }
   ]
  },
  {
   "title": "Critical Risk Events (2h)",
   "type": "table",
   "description": "Risk events with status \"critical\" in the last 2 hours",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"fraud-metrics\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"fraud_events\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.risk_level == \"critical\")\r\n  |> keep(columns: [\"_time\", \"user_id\", \"fraud_score\", \"risk_level\"])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n"
    }
   ]
  },
  {
   "title": "Top 50 Risky Users (2h)",
   "type": "table",
   "description": "Only users with risk level \"critical\", \"high\" and \"medium\" are included",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"fraud-metrics\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r._measurement == \"fraud_events\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.risk_level == \"critical\" or\r\n                        r.risk_level == \"high\" or\r\n                        r.risk_level == \"medium\")\r\n  |> keep(columns: [\"user_id\", \"fraud_score\", \"risk_level\"])\r\n  |> group()\r\n  |> sort(columns: [\"fraud_score\"], desc: true)\r\n  |> limit(n: 50)\r\n"
    }
   ]
  }
 ]
}